research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

chat_task:
  description: >
    Use the conversation history to build your response to the user:
    {history}
    Respond to the user's message: {user_message},
    Make the response at maximum three paragraphs.
  expected_output: >
    Your output should be a relevant, accurate, and engaging response that directly 
    addresses the user's query or continues the conversation logically.
  agent: assistant
